//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrera()
        {
            this.CarrerasDeUsuarios = new HashSet<CarrerasDeUsuario>();
            this.SemestresDeCarreras = new HashSet<SemestresDeCarrera>();
        }
    
        public int id_carrera { get; set; }
        public string nombre_carrera { get; set; }
        public Nullable<int> id_facultad { get; set; }
    
        public virtual Facultade Facultade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrerasDeUsuario> CarrerasDeUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemestresDeCarrera> SemestresDeCarreras { get; set; }
    }
}
