//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carreras()
        {
            this.CarrerasDeUsuarios = new HashSet<CarrerasDeUsuarios>();
            this.SemestresDeCarreras = new HashSet<SemestresDeCarreras>();
        }
    
        public int id_carrera { get; set; }
        public string nombre_carrera { get; set; }
        public Nullable<int> id_facultad { get; set; }
    
        public virtual Facultades Facultades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrerasDeUsuarios> CarrerasDeUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemestresDeCarreras> SemestresDeCarreras { get; set; }
    }
}
