//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int id_horario { get; set; }
        public Nullable<int> id_aula { get; set; }
        public Nullable<int> id_asignatura { get; set; }
        public int no_grupo { get; set; }
        public Nullable<int> id_diaDisponibilidad { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Aula Aula { get; set; }
        public virtual DiaDisponibilidade DiaDisponibilidade { get; set; }
    }
}
