//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SandrelenaEntities : DbContext
    {
        public SandrelenaEntities()
            : base("name=SandrelenaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividade> Actividades { get; set; }
        public virtual DbSet<Asignatura> Asignaturas { get; set; }
        public virtual DbSet<AsignaturasDeSemestre> AsignaturasDeSemestres { get; set; }
        public virtual DbSet<Aula> Aulas { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<CarrerasDeUsuario> CarrerasDeUsuarios { get; set; }
        public virtual DbSet<DiaDisponibilidade> DiaDisponibilidades { get; set; }
        public virtual DbSet<Facultade> Facultades { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<GruposDeUsuario> GruposDeUsuarios { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Nota> Notas { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<PermisosDeRole> PermisosDeRoles { get; set; }
        public virtual DbSet<Prerrequisito> Prerrequisitos { get; set; }
        public virtual DbSet<ProfesoresDeAsignatura> ProfesoresDeAsignaturas { get; set; }
        public virtual DbSet<RegistrosDeActividade> RegistrosDeActividades { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Semestre> Semestres { get; set; }
        public virtual DbSet<SemestresDeCarrera> SemestresDeCarreras { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
