//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosDeRole
    {
        public int id_permisos_roles { get; set; }
        public Nullable<int> id_permiso { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual Permiso Permiso { get; set; }
        public virtual Role Role { get; set; }
    }
}
