//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prerrequisito
    {
        public int id_prerrequisito { get; set; }
        public Nullable<int> id_asignatura { get; set; }
        public Nullable<int> id_asignatura_requisito { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Asignatura Asignatura1 { get; set; }
    }
}
