//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosDeActividade
    {
        public int id_registros_actividades { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Actividade Actividade { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
