//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandrelenaWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aulas
    {
        public Aulas()
        {
            this.Horarios = new HashSet<Horarios>();
        }
    
        public int id_aula { get; set; }
        public string nombre_aula { get; set; }
        public bool isLab { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Horarios> Horarios { get; set; }
    }
}
