//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandrelenaWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras
    {
        public Carreras()
        {
            this.Semestres = new HashSet<Semestres>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id_carrera { get; set; }
        public string nombre_carrera { get; set; }
        public Nullable<int> id_facultad { get; set; }
        public bool isActive { get; set; }
    
        public virtual Facultades Facultades { get; set; }
        public virtual ICollection<Semestres> Semestres { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
