//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandrelenaWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultades
    {
        public Facultades()
        {
            this.Carreras = new HashSet<Carreras>();
        }
    
        public int id_facultad { get; set; }
        public string nombre_facultad { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Carreras> Carreras { get; set; }
    }
}
