//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandrelenaWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SandrelenaEntities_DbContext : DbContext
    {
        public SandrelenaEntities_DbContext()
            : base("name=SandrelenaEntities_ConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignaturas> Asignaturas { get; set; }
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<Facultades> Facultades { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Prerrequisitos> Prerrequisitos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Semestres> Semestres { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
